/*
 * Copyright (c) 2026 TOKITA Hiroshi
 *
 * SPDX-License-Identifier: Apache-2.0
 */

syntax = "proto3";

package arduino;

import "arduino_opts.proto";
import "google/protobuf/empty.proto";
import "google/protobuf/wrappers.proto";

enum SerialParity {
	SERIAL_PARITY_UNSPECIFIED = 0;
	SERIAL_PARITY_EVEN = 0x1;
	SERIAL_PARITY_ODD = 0x2;
	SERIAL_PARITY_NONE = 0x3;
	SERIAL_PARITY_MARK = 0x4;
	SERIAL_PARITY_SPACE = 0x5;
	SERIAL_PARITY_MASK = 0xF;
}

enum SerialStopBit {
	SERIAL_STOP_BIT_UNSPECIFIED = 0;
	SERIAL_STOP_BIT_1 = 0x10;
	SERIAL_STOP_BIT_1_5 = 0x20;
	SERIAL_STOP_BIT_2 = 0x30;
	SERIAL_STOP_BIT_MASK = 0xF0;
}

enum SerialDataLen {
	SERIAL_DATA_UNSPECIFIED = 0;
	SERIAL_DATA_5 = 0x100;
	SERIAL_DATA_6 = 0x200;
	SERIAL_DATA_7 = 0x300;
	SERIAL_DATA_8 = 0x400;
	SERIAL_DATA_MASK = 0xF00;
}

message HardwareSerialBeginRequest {
	uint64 baudrate = 1 [ (arduino.cpp_type) = "unsigned long", (arduino.field_cpp_name) = "arg0" ];
}

message HardwareSerialBeginConfigRequest {
	uint64 baudrate = 1 [ (arduino.cpp_type) = "unsigned long", (arduino.field_cpp_name) = "arg0" ];
	uint32 config = 2 [ (arduino.cpp_type) = "uint16_t", (arduino.field_cpp_name) = "arg1" ];
}

service HardwareSerial {
	option (arduino.base_services) = "Stream";

	rpc BeginBaud(HardwareSerialBeginRequest) returns (google.protobuf.Empty) {
		option (arduino.cpp_name) = "begin";
	}
	rpc BeginBaudConfig(HardwareSerialBeginConfigRequest) returns (google.protobuf.Empty) {
		option (arduino.cpp_name) = "begin";
	}
	rpc End(google.protobuf.Empty) returns (google.protobuf.Empty) {
		option (arduino.cpp_name) = "end";
	}
	rpc IsValid(google.protobuf.Empty) returns (google.protobuf.BoolValue) {
		option (arduino.cpp_name) = "operator bool";
	}
}
