#!/usr/bin/env python3
#
# Copyright (c) 2026 TOKITA Hiroshi
#
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from pathlib import PurePosixPath
from typing import Iterator, List, Tuple

from google.protobuf.descriptor_pb2 import EnumDescriptorProto

__all__ = [
    "EnumRenderer",
]


class EnumRenderer:
    """Renders top-level protobuf enums as a C-compatible type header."""

    def __init__(self, proto_name: str, enums: List[EnumDescriptorProto]) -> None:
        self._proto_name = proto_name
        self._enums = enums

    def __iter__(self) -> Iterator[Tuple[str, str]]:
        yield self._header_name(), self._render_header_content()

    def _header_name(self) -> str:
        return f"{PurePosixPath(self._proto_name).stem}_types.h"

    def _render_header_content(self) -> str:
        lines = [
            "// Generated by protoc-gen-arduinoif. DO NOT EDIT.",
            "",
            "#pragma once",
            "",
            "#include <stdint.h>",
            "",
        ]

        for enum_desc in self._enums:
            lines.extend([f"typedef enum {enum_desc.name} {{"])
            lines.extend(f"  {v.name} = {v.number}," for v in enum_desc.value)
            lines.extend([f"}} {enum_desc.name};", ""])

        return "\n".join(lines)
