CONFIG_GPIO=y
CONFIG_ARDUINO_API=y
CONFIG_SPI=y
CONFIG_EEPROM=yCONFIG_FLASH_PAGE_LAYOUT

CONFIG_PWM=y
CONFIG_ADC=y
CONFIG_GPIO_GET_DIRECTION=y

CONFIG_LOG=y
CONFIG_MAIN_STACK_SIZE=8192
CONFIG_ENTROPY_GENERATOR=y

CONFIG_NVS=y
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y

CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_NVS_LOG_LEVEL_DBG=y
CONFIG_REBOOT=y
CONFIG_MPU_ALLOW_FLASH_WRITE=y

CONFIG_FLASH_PAGE_LAYOUT=y
