/*
 * Copyright (c) 2026 TOKITA Hiroshi
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#pragma once

#define ZARD_CONNECTOR arduino_header

#define ZARD_ARDUINO_HEADER_R3_PIN_NAME_A_0 A0
#define ZARD_ARDUINO_HEADER_R3_PIN_NAME_A_1 A1
#define ZARD_ARDUINO_HEADER_R3_PIN_NAME_A_2 A2
#define ZARD_ARDUINO_HEADER_R3_PIN_NAME_A_3 A3
#define ZARD_ARDUINO_HEADER_R3_PIN_NAME_A_4 A4
#define ZARD_ARDUINO_HEADER_R3_PIN_NAME_A_5 A5

#define ZARD_ARDUINO_HEADER_R3_PIN_NAME_D_6  D0
#define ZARD_ARDUINO_HEADER_R3_PIN_NAME_D_7  D1
#define ZARD_ARDUINO_HEADER_R3_PIN_NAME_D_8  D2
#define ZARD_ARDUINO_HEADER_R3_PIN_NAME_D_9  D3
#define ZARD_ARDUINO_HEADER_R3_PIN_NAME_D_10 D4
#define ZARD_ARDUINO_HEADER_R3_PIN_NAME_D_11 D5
#define ZARD_ARDUINO_HEADER_R3_PIN_NAME_D_12 D6
#define ZARD_ARDUINO_HEADER_R3_PIN_NAME_D_13 D7
#define ZARD_ARDUINO_HEADER_R3_PIN_NAME_D_14 D8
#define ZARD_ARDUINO_HEADER_R3_PIN_NAME_D_15 D9
#define ZARD_ARDUINO_HEADER_R3_PIN_NAME_D_16 D10
#define ZARD_ARDUINO_HEADER_R3_PIN_NAME_D_17 D11
#define ZARD_ARDUINO_HEADER_R3_PIN_NAME_D_18 D12
#define ZARD_ARDUINO_HEADER_R3_PIN_NAME_D_19 D13
#define ZARD_ARDUINO_HEADER_R3_PIN_NAME_D_20 D14
#define ZARD_ARDUINO_HEADER_R3_PIN_NAME_D_21 D15

#define ZARD_ARDUINO_HEADER_R3_IS_ANALOG_0   1
#define ZARD_ARDUINO_HEADER_R3_IS_ANALOG_1   1
#define ZARD_ARDUINO_HEADER_R3_IS_ANALOG_2   1
#define ZARD_ARDUINO_HEADER_R3_IS_ANALOG_3   1
#define ZARD_ARDUINO_HEADER_R3_IS_ANALOG_4   1
#define ZARD_ARDUINO_HEADER_R3_IS_ANALOG_5   1
#define ZARD_ARDUINO_HEADER_R3_IS_DIGITAL_6  1
#define ZARD_ARDUINO_HEADER_R3_IS_DIGITAL_7  1
#define ZARD_ARDUINO_HEADER_R3_IS_DIGITAL_8  1
#define ZARD_ARDUINO_HEADER_R3_IS_DIGITAL_9  1
#define ZARD_ARDUINO_HEADER_R3_IS_DIGITAL_10 1
#define ZARD_ARDUINO_HEADER_R3_IS_DIGITAL_11 1
#define ZARD_ARDUINO_HEADER_R3_IS_DIGITAL_12 1
#define ZARD_ARDUINO_HEADER_R3_IS_DIGITAL_13 1
#define ZARD_ARDUINO_HEADER_R3_IS_DIGITAL_14 1
#define ZARD_ARDUINO_HEADER_R3_IS_DIGITAL_15 1
#define ZARD_ARDUINO_HEADER_R3_IS_DIGITAL_16 1
#define ZARD_ARDUINO_HEADER_R3_IS_DIGITAL_17 1
#define ZARD_ARDUINO_HEADER_R3_IS_DIGITAL_18 1
#define ZARD_ARDUINO_HEADER_R3_IS_DIGITAL_19 1
#define ZARD_ARDUINO_HEADER_R3_IS_DIGITAL_20 1
#define ZARD_ARDUINO_HEADER_R3_IS_DIGITAL_21 1

#if DT_NODE_EXISTS(DT_NODELABEL(arduino_adc))
#define ZARD_ADC_CONNECTOR arduino_adc
#endif

#if DT_NODE_EXISTS(DT_NODELABEL(arduino_pwm))
#define ZARD_PWM_CONNECTOR arduino_pwm
#endif
