name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build Arduino-API Zephyr samples
    runs-on: ubuntu-latest
    container: zephyrprojectrtos/ci-base:latest
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
      CCACHE_IGNOREOPTIONS: -specs=*
      MODULE_PATH: ../modules/lib/Arduino-Zephyr-API

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
          path: subfolder

      - name: Fix module path, list needed HALs
        run: |
          mkdir -p $(dirname $MODULE_PATH) && mv subfolder $MODULE_PATH

      - name: Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          toolchains: arm-zephyr-eabi
          manifest-file-name: ${{ env.MODULE_PATH }}/west.yml
          enable-ccache: false

      - name: Add manifest path as module
        run: |
          echo EXTRA_ZEPHYR_MODULES="$(pwd)/$MODULE_PATH" >> $GITHUB_ENV

      - name: Initialize
        run: |
          west blobs --auto-accept fetch arduinocore-zephyr

      - name: Setup Rust toolchain
        run: |
          wget https://sh.rustup.rs
          mv index.html rustup_install.sh
          bash rustup_install.sh -y
          /root/.cargo/bin/rustup default stable
          /root/.cargo/bin/rustup target add thumbv6m-none-eabi thumbv7em-none-eabihf thumbv7em-none-eabi thumbv7m-none-eabi
          echo "/root/.cargo/bin" >> $GITHUB_PATH

      - name: Build fade
        run: |
          west build -p -b arduino_nano_33_ble/nrf52840/sense $MODULE_PATH/samples/fade

      - name: Build i2cdemo
        run: |
          west build -p -b arduino_nano_33_ble/nrf52840/sense $MODULE_PATH/samples/i2cdemo

      - name: Build adc
        run: |
          west build -p -b beagleconnect_freedom/cc1352p7 $MODULE_PATH/samples/analog_input

      - name: Archive firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: Arduino-Zephyr-API/build/zephyr/zephyr.*
